### ISSUE TITLE
How can i implement CardListView with custom card layout 

### ISSUE THREAD

**Issue by ajitbohra** [gabrielemariotti/cardslib#164]
- have gone through the sample code & documentation but still confused
- I want to create cardlistview with custom card view

**Comment by alirezaznz** [comment]
Hello @gabrielemariotti 
i want to set a gauge from another library in a layout and then use it in a card
the problem is when the card is set its a blank gauge with no parameters has set
 View Speedmetter =LayoutInflater.from(getApplicationContext()).inflate(R.layout.native_card_thumbnail_layout,null);
        speedometer = (SpeedometerGauge) Speedmetter.findViewById(R.id.speedometer);
 Card card = new Card(speedometer.getContext(),R.layout.native_card_thumbnail_layout);

can u help me with this please?
Thank you
