### ISSUE TITLE
import cardslib core(android 4.1.2) to my project(android 4.0.3)

### ISSUE THREAD

**Issue by andrewhlleung** [gabrielemariotti/cardslib#389]
I imported cardslib version 1.8.0 with new name "cardcore" to my eclipse.
add java folder to "user as source folder"
in properties, selected Android 4.1.2 in Project Build Target.
checked "Is Library"
its no error.

I create a new project with Android 4.0.3
after add library cardcore to this project.
i got this error ".....No resource found that matches the given name: attr 'android:fontFamily'."

also this new project cannot auto build R.java

**Comment by AkshayChordiya** [comment]
I recommend to switch over Android Studio. 
Anyways no offense if you use Eclipse yet. 

About resource found for font family :
I guess that attribute is available since Jellybean, so I suggest you too delete that attribute because your target version is Ice Cream Sandwich. 

I don't know or remember 2nd one because I left Eclipse, a long time ago.

**Comment by gabrielemariotti** [comment]
First of all.
If you are working with 1.8.0, I suggest you using the 1.9.1 or 2.0.1.

Then:
No resource found that matches the given name: attr 'android:fontFamily'."
The 1.x releases need to be compiled with api 16.
The 2.x releases nedd to be compiled with api 21.

**Comment by andrewhlleung** [comment]
I change to use 1.9.0. And remove all fontfamily line in xml.
Thats ok now.

If use 2.0.1, some error.
