### ISSUE TITLE
ListView or Recyclerview ?

### ISSUE THREAD

**Issue by shic** [gabrielemariotti/cardslib#471]
When we use native android view, then the Recyclerview may be better. But when we use this lib, I found ListView is more powerful than Recyclerview. Am I right? Are there  something that Recyclerview can do, but listView can not?

**Comment by gabrielemariotti** [comment]
Yes you are right.
The `ListView` was introduced in the lib at the beginning (2 years ago) and it has a lot of built-in features. 
I will try to port these feature in the `RecyclerView` because today all list should be switched with the RecyclerView.
And yes, in the future may be the `RecyclerView` will have features not supported by `ListView`

**Comment by shic** [comment]
Thanks for the response! But for now maybe it is better for me to use ListView, because The RecyclerView may be not have a lot features and more difficult to use. I will wait for your update of RecyclerView.
