### ISSUE TITLE
CardThumbnail is not show

### ISSUE THREAD

**Issue by feherbt** [gabrielemariotti/cardslib#48]
I made a simple activity, but the image (thumbnail) is not showing, Please help me, what is the problem.

```
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    Card card = new Card(getApplicationContext());

    CardThumbnail thumb = new CardThumbnail(getApplicationContext());

    // Set resource
    thumb.setDrawableResource(R.drawable.ic_launcher);

    // Add thumbnail to a card
    card.addCardThumbnail(thumb);
    CardView cardView = (CardView) findViewById(R.id.carddemo);
    cardView.setCard(card);
}
```

**Comment by jwiesmann** [comment]
Hi, in case someone might find it useful. 
I had a similar problem today and the root cause was that my xml file had the wrong namespace.

Android Studio "tried" to help me and automatically added:
- xmlns:card="http://schemas.android.com/tools"

instead of
- xmlns:card="http://schemas.android.com/apk/res-auto"

That is kind of confusing since the CardHeader worked still perfectly fine!

Great library!
